workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - build

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle
  paths:
    - .gradle/
    - .gradle/wrapper/
    - .gradle/caches/

build_offline_release_apk:
  image: eclipse-temurin:17-jdk-jammy
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  variables:
    ANDROID_SDK_ROOT: /sdk

  before_script:
    - apt-get update
    - apt-get install -y wget unzip
    - mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
    - cd $ANDROID_SDK_ROOT/cmdline-tools
    - wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
    - unzip -q tools.zip
    - rm -rf latest
    - mv cmdline-tools latest
    - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
    - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses > /dev/null || true
    - sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-36" "build-tools;36.0.0"
    - cd $CI_PROJECT_DIR
    - chmod +x ./gradlew

  script:
    - ./gradlew --no-daemon :app:lintOfflineRelease :app:assembleOfflineRelease

  artifacts:
    name: "switchly-offline-apk-$CI_COMMIT_SHORT_SHA"
    when: on_success
    expire_in: 30 days
    paths:
      - app/build/outputs/apk/offline/release/*.apk
