package at.saltyy.switchly.auth

import android.app.Activity
import android.content.Context
import android.os.CancellationSignal
import android.util.Log
import android.widget.Toast
import androidx.core.content.ContextCompat
import androidx.credentials.CredentialManager
import androidx.credentials.CredentialManagerCallback
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.google.firebase.FirebaseApp
import com.google.firebase.FirebaseOptions
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import org.json.JSONObject
import at.saltyy.switchly.R

/**
 * Authentication runtime:
 * - Credential Manager + Google ID (googleid) for sign-in
 * - FirebaseAuth for backend auth
 *
 * IMPORTANT:
 * - This must NOT crash if Firebase isn't configured yet (e.g. missing google-services.json in /app).
 */
object AuthRuntime {

    private const val TAG = "AuthRuntime"

    private data class GoogleServicesInfo(
        val mobilesdkAppId: String,
        val apiKey: String,
        val projectId: String,
        val projectNumber: String?,
        val storageBucket: String?,
        val webClientId: String?
    )

    private fun readGoogleServicesInfoOrNull(context: Context): GoogleServicesInfo? {
        return runCatching {
            val jsonText = context.assets.open("google-services.json").bufferedReader().use { it.readText() }
            val root = JSONObject(jsonText)

            val projectInfo = root.getJSONObject("project_info")
            val projectNumber = projectInfo.optString("project_number", null)
            val projectId = projectInfo.optString("project_id", null) ?: return@runCatching null
            val storageBucket = projectInfo.optString("storage_bucket", null)

            val client = root.getJSONArray("client").getJSONObject(0)
            val clientInfo = client.getJSONObject("client_info")
            val mobilesdkAppId = clientInfo.optString("mobilesdk_app_id", null) ?: return@runCatching null

            val apiKeyArr = client.optJSONArray("api_key")
            val apiKey = apiKeyArr?.optJSONObject(0)?.optString("current_key", null) ?: return@runCatching null

            // Web OAuth client id (client_type == 3) for Credential Manager / Google Sign-In.
            var webClientId: String? = null
            val oauthClients = client.optJSONArray("oauth_client")
            if (oauthClients != null) {
                for (i in 0 until oauthClients.length()) {
                    val obj = oauthClients.getJSONObject(i)
                    if (obj.optInt("client_type") == 3) {
                        webClientId = obj.optString("client_id", null)
                        break
                    }
                }
            }

            GoogleServicesInfo(
                mobilesdkAppId = mobilesdkAppId,
                apiKey = apiKey,
                projectId = projectId,
                projectNumber = projectNumber,
                storageBucket = storageBucket,
                webClientId = webClientId
            )
        }.getOrNull()
    }

    private fun ensureFirebaseAppOrNull(context: Context): FirebaseApp? {
        // 1) normal initialization using resources generated by google-services plugin
        FirebaseApp.getApps(context).firstOrNull()?.let { return it }

        val ctx = context.applicationContext
        val fromResources = runCatching { FirebaseApp.initializeApp(ctx) }.getOrNull()
        if (fromResources != null) return fromResources

        // 2) fallback: parse google-services.json from APK assets (generated at build time)
        val info = readGoogleServicesInfoOrNull(ctx) ?: return null

        val options = FirebaseOptions.Builder()
            .setApplicationId(info.mobilesdkAppId)
            .setApiKey(info.apiKey)
            .setProjectId(info.projectId)
            .apply {
                info.projectNumber?.let { setGcmSenderId(it) }
                info.storageBucket?.let { setStorageBucket(it) }
            }
            .build()

        return runCatching { FirebaseApp.initializeApp(ctx, options) }.getOrNull()
    }

    private fun firebaseAuthOrNull(context: Context): FirebaseAuth? {
        return try {
            FirebaseAuth.getInstance()
        } catch (e: IllegalStateException) {
            // Try to initialize Firebase (returns null if options are missing)
            val app = ensureFirebaseAppOrNull(context)
            if (app == null) {
                Log.w(TAG, "FirebaseApp not initialized (missing google-services.json?)")
                null
            } else {
                runCatching { FirebaseAuth.getInstance(app) }.getOrNull()
            }
        } catch (t: Throwable) {
            Log.e(TAG, "firebaseAuthOrNull unexpected error", t)
            null
        }
    }

    private fun serverClientIdOrNull(activity: Activity): String? {
        // Generated by the Google Services plugin (from google-services.json).
        // We use getIdentifier() so this file still compiles even if the file/plugin is missing.
        val resId = activity.resources.getIdentifier("default_web_client_id", "string", activity.packageName)
        if (resId == 0) {
            // Fallback: read Web client id from google-services.json asset.
            return readGoogleServicesInfoOrNull(activity)?.webClientId
        }

        val value = activity.getString(resId)
        return value.takeUnless { it.isBlank() || it.startsWith("YOUR_") }
    }

    fun startSignIn(
        activity: Activity,
        onResult: (Boolean, String?) -> Unit
    ) {
        val auth = firebaseAuthOrNull(activity)
        if (auth == null) {
            val msg = activity.getString(R.string.auth_firebase_not_configured)
            Toast.makeText(activity, msg, Toast.LENGTH_LONG).show()
            onResult(false, msg)
            return
        }

        val serverClientId = serverClientIdOrNull(activity)
        if (serverClientId == null) {
            val msg = activity.getString(R.string.auth_missing_google_server_client_id)
            Toast.makeText(activity, msg, Toast.LENGTH_LONG).show()
            onResult(false, msg)
            return
        }

        val credentialManager = CredentialManager.create(activity)

        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            .setFilterByAuthorizedAccounts(true)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val cancellationSignal = CancellationSignal()
        val executor = ContextCompat.getMainExecutor(activity)

        credentialManager.getCredentialAsync(
            activity,
            request,
            cancellationSignal,
            executor,
            object : CredentialManagerCallback<GetCredentialResponse, GetCredentialException> {
                override fun onResult(result: GetCredentialResponse) {
                    // Handle Sign in with Google result right here so lint can verify
                    // that GoogleIdTokenCredential is actually used when GetGoogleIdOption is used.
                    val credential = result.credential

                    if (credential is CustomCredential &&
                        credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                    ) {
                        try {
                            val googleCred = GoogleIdTokenCredential.createFrom(credential.data)
                            val idToken = googleCred.idToken
                            firebaseAuthWithGoogle(activity, auth, idToken, onResult)
                            return
                        } catch (e: GoogleIdTokenParsingException) {
                            Log.e(TAG, "Google ID token parsing failed", e)
                            val msg = activity.getString(R.string.auth_failed_to_process_google_token)
                            Toast.makeText(activity, msg, Toast.LENGTH_SHORT).show()
                            onResult(false, msg)
                            return
                        } catch (t: Throwable) {
                            Log.e(TAG, "Unexpected error handling Google credential", t)
                            val msg = activity.getString(R.string.auth_unexpected_error_sign_in)
                            Toast.makeText(activity, msg, Toast.LENGTH_SHORT).show()
                            onResult(false, msg)
                            return
                        }
                    }

                    // User cancelled or unsupported credential type
                    Log.w(TAG, "Unsupported or cancelled credential: $credential")
                    val msg = activity.getString(R.string.auth_sign_in_cancelled)
                    Toast.makeText(activity, msg, Toast.LENGTH_SHORT).show()
                    onResult(false, msg)
                }

                override fun onError(e: GetCredentialException) {
                    handleCredentialError(activity, e, onResult)
                }
            }
        )
    }

    private fun handleCredentialError(
        activity: Activity,
        e: GetCredentialException,
        onResult: (Boolean, String?) -> Unit
    ) {
        when (e) {
            is NoCredentialException -> {
                Log.w(TAG, "No credentials available", e)
                val msg = activity.getString(R.string.auth_no_matching_google_accounts_found)
                Toast.makeText(activity, msg, Toast.LENGTH_SHORT).show()
                onResult(false, msg)
            }

            else -> {
                Log.e(TAG, "getCredential failed", e)
                val msg = activity.getString(R.string.auth_sign_in_failed_generic)
                Toast.makeText(activity, msg, Toast.LENGTH_SHORT).show()
                onResult(false, msg)
            }
        }
    }

    private fun firebaseAuthWithGoogle(
        activity: Activity,
        auth: FirebaseAuth,
        idToken: String,
        onResult: (Boolean, String?) -> Unit
    ) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(credential)
            .addOnCompleteListener(activity) { task ->
                if (task.isSuccessful) {
                    Log.d(TAG, "Firebase sign-in success")
                    onResult(true, null)
                } else {
                    val error = task.exception?.localizedMessage
                        ?: activity.getString(R.string.auth_sign_in_failed_generic)
                    Log.e(TAG, "Firebase sign-in failed: $error", task.exception)
                    onResult(false, error)
                }
            }
    }

    fun signOut(context: Context, onDone: () -> Unit) {
        try {
            firebaseAuthOrNull(context)?.signOut()
            Toast.makeText(context, context.getString(R.string.settings_signed_out), Toast.LENGTH_SHORT).show()
        } catch (t: Throwable) {
            Log.e(TAG, "Error during signOut", t)
        }
        onDone()
    }

    /**
     * Returns the current Firebase UID (or null if not signed in / Firebase not configured).
     */
    fun uid(): String? = runCatching { FirebaseAuth.getInstance().currentUser?.uid }.getOrNull()
}
